name:                find-filter-run
version:             0.1.0.0
github:              "anickaburova/find-filter-run"
license:             BSD3
author:              "Anicka Burova"
maintainer:          "anickaburova@gmail.com"
copyright:           "2018 Anicka Burova"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/find-filter-run#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- utf8-string
- process

library:
  source-dirs: src

executables:
  ffr:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - find-filter-run
    - cmdargs
    - filepath
    - bytestring

tests:
  find-filter-run-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - find-filter-run
